"""Hand-written correct solutions, one per problem.

SOLUTIONS is the single source of truth for "what does a correct answer
to this problem look like" - verify_all_solvable.py imports it to check
every problem's expected_output actually matches what correct code
produces, and gui/problem_view.py's Show Solution button imports it to
reveal a solution to a student who has already attempted the problem.

Each entry is one of two shapes, and verify_all_solvable.py tells them
apart by whether the text starts with "def ": a plain top-level script
(the legacy I/O-topic style, run directly through core.runner since it
reads via input() rather than taking arguments), or a real function
definition matching the problem's function_name (every other topic,
run through core.submission exactly like a student submission would be,
since it takes its test data as arguments).
"""

SOLUTIONS = {
    "io_001": "name = input()\nprint(f'Hello, {name}!')\n",
    "io_002": "word1 = input()\nword2 = input()\nprint(word1)\nprint(word2)\n",
    "io_003": "word1 = input()\nword2 = input()\nprint(word1 + ', ' + word2)\n",
    "io_004": "value = float(input())\nprint(value)\n",
    "io_005": "name = input()\nage = int(input())\nprint(f'{name} is {age} years old.')\n",

    # Loops (05_loops): function-based, since these problems take arguments
    # instead of reading via input() - see core/submission.py for why a
    # solution shaped like "def name(...): ... return ..." is run through
    # run_and_grade_all rather than run_code directly.
    "loops_001": "def sum_of_odd_numbers_up_to(n):\n    total = 0\n    for i in range(1, n + 1):\n        if i % 2 == 1:\n            total += i\n    return total\n",
    "loops_002": "def count_divisible_by(n, divisor):\n    count = 0\n    for i in range(1, n + 1):\n        if i % divisor == 0:\n            count += 1\n    return count\n",
    "loops_003": "def sum_of_range(start, end):\n    total = 0\n    for i in range(start, end + 1):\n        total += i\n    return total\n",
    "loops_004": "def multiplication_table(n):\n    table = []\n    for i in range(1, 6):\n        table.append(n * i)\n    return table\n",
    "loops_005": "def countdown_by_step(n, step):\n    result = []\n    current = n\n    while current >= 0:\n        result.append(current)\n        current -= step\n    return result\n",
    "loops_006": "def factorial(n):\n    total = 1\n    for i in range(1, n + 1):\n        total *= i\n    return total\n",
    "loops_007": "def digit_sum(n):\n    total = 0\n    while n > 0:\n        total += n % 10\n        n //= 10\n    return total\n",
    "loops_008": "def count_digits(n):\n    count = 0\n    while n > 0:\n        count += 1\n        n //= 10\n    return count\n",
    "loops_009": "def reverse_number(n):\n    reversed_n = 0\n    while n > 0:\n        digit = n % 10\n        reversed_n = reversed_n * 10 + digit\n        n //= 10\n    return reversed_n\n",
    "loops_010": "def number_triangle(n):\n    rows = []\n    for i in range(1, n + 1):\n        row = ''\n        for x in range(1, i + 1):\n            if x > 1:\n                row = row + ' '\n            row = row + str(x)\n        rows.append(row)\n    return '\\n'.join(rows)\n",
    "loops_011": "def count_vowels(word):\n    vowels = 'aeiouAEIOU'\n    count = 0\n    for ch in word:\n        if ch in vowels:\n            count += 1\n    return count\n",
    "loops_012": "def count_occurrences(word, letter):\n    count = 0\n    for ch in word:\n        if ch == letter:\n            count += 1\n    return count\n",
    "loops_013": "def sum_of_multiples_of_either(limit, a, b):\n    total = 0\n    for i in range(1, limit):\n        if i % a == 0 or i % b == 0:\n            total += i\n    return total\n",
    "loops_014": "def power_without_operator(base, exp):\n    result = 1\n    for i in range(exp):\n        result *= base\n    return result\n",
    "loops_015": "def is_prime(n):\n    if n < 2:\n        return False\n    for i in range(2, n):\n        if n % i == 0:\n            return False\n    return True\n",
    "loops_016": "def gcd_of_two(a, b):\n    while b != 0:\n        a, b = b, a % b\n    return a\n",
    "loops_017": "def fibonacci_at(n):\n    a, b = 0, 1\n    for i in range(n):\n        a, b = b, a + b\n    return a\n",
    "loops_018": "def digital_root(n):\n    while n >= 10:\n        total = 0\n        while n > 0:\n            total += n % 10\n            n //= 10\n        n = total\n    return n\n",
    "loops_019": "def triangle_pattern(n):\n    rows = []\n    for i in range(1, n + 1):\n        rows.append('*' * i)\n    return '\\n'.join(rows)\n",
    "loops_020": "def collatz_steps(n):\n    steps = 0\n    while n != 1:\n        if n % 2 == 0:\n            n = n // 2\n        else:\n            n = 3 * n + 1\n        steps += 1\n    return steps\n",
    "loops_debug_001": "def sum_of_range(start, end):\n    total = 0\n    for i in range(start, end + 1):\n        total += i\n    return total\n",
    "loops_debug_002": "def factorial(n):\n    total = 1\n    for i in range(1, n + 1):\n        total *= i\n    return total\n",
    "loops_debug_003": "def count_divisible_by(n, divisor):\n    count = 0\n    for i in range(1, n + 1):\n        if i % divisor == 0:\n            count += 1\n    return count\n",
    "loops_debug_004": "def is_prime(n):\n    if n < 2:\n        return False\n    for i in range(2, n):\n        if n % i == 0:\n            return False\n    return True\n",

    # Variables (01_variables)
    "variables_001": "def total_after_tax(price, tax_rate):\n    return price + price * tax_rate\n",
    "variables_002": "def temperature_swing(morning_temp, evening_temp):\n    return evening_temp - morning_temp\n",
    "variables_003": "def time_to_seconds(hours, minutes):\n    return hours * 3600 + minutes * 60\n",
    "variables_004": "def split_the_bill_with_tip(total, people, tip_rate):\n    return (total + total * tip_rate) / people\n",
    "variables_005": "def age_gap(age1, age2):\n    return abs(age1 - age2)\n",
    "variables_006": "def exceeds_when_converted(celsius, fahrenheit_limit):\n    fahrenheit = celsius * 9 / 5 + 32\n    return fahrenheit > fahrenheit_limit\n",
    "variables_007": "def remaining_after_purchase(balance, price, quantity):\n    return balance - price * quantity\n",
    "variables_008": "def paces_to_meters(paces, pace_length):\n    return paces * pace_length\n",
    "variables_009": "def is_within_one_year(age1, age2):\n    return abs(age1 - age2) <= 1\n",
    "variables_010": "def formatted_id(first, last, id_number):\n    return f'{last}, {first} (#{id_number})'\n",
    "variables_011": "def discounted_price(price, discount_percent):\n    return price - price * discount_percent / 100\n",
    "variables_012": "def speed_from_distance_time(distance, time):\n    return distance / time\n",
    "variables_013": "def total_distance_two_legs(speed1, time1, speed2, time2):\n    return speed1 * time1 + speed2 * time2\n",
    "variables_014": "def profit(revenue, cost):\n    return revenue - cost\n",
    "variables_015": "def year_someone_turns_age(birth_year, target_age):\n    return birth_year + target_age\n",
    "variables_016": "def flag_to_bit(is_active):\n    return int(is_active)\n",
    "variables_017": "def average_speed(distance, time1, time2):\n    return distance / (time1 + time2)\n",
    "variables_018": "def can_afford(balance, price):\n    return balance >= price\n",
    "variables_019": "def total_inches(feet, inches):\n    return feet * 12 + inches\n",
    "variables_020": "def net_change(start_value, end_value):\n    return end_value - start_value\n",
    "variables_debug_001": "def speed_from_distance_time(distance, time):\n    return distance / time\n",
    "variables_debug_002": "def discounted_price(price, discount_percent):\n    return price - price * discount_percent / 100\n",
    "variables_debug_003": "def formatted_id(first, last, id_number):\n    return f'{last}, {first} (#{id_number})'\n",
    "variables_debug_004": "def remaining_after_purchase(balance, price, quantity):\n    return balance - price * quantity\n",

    # Operators (02_operators)
    "operators_001": "def total_with_compound_discount(price, discount1, discount2):\n    after_first = price - price * discount1 / 100\n    after_second = after_first - after_first * discount2 / 100\n    return after_second\n",
    "operators_002": "def is_between_exclusive(n, low, high):\n    return low < n < high\n",
    "operators_003": "def items_left_over(total, group_size):\n    return total % group_size\n",
    "operators_004": "def pages_needed(items, items_per_page):\n    return (items + items_per_page - 1) // items_per_page\n",
    "operators_005": "def is_strictly_increasing(a, b, c):\n    return a < b < c\n",
    "operators_006": "def same_sign(a, b):\n    return (a > 0 and b > 0) or (a < 0 and b < 0)\n",
    "operators_007": "def weighted_score(score1, weight1, score2, weight2):\n    return score1 * weight1 + score2 * weight2\n",
    "operators_008": "def distance_squared(x1, y1, x2, y2):\n    return (x2 - x1) ** 2 + (y2 - y1) ** 2\n",
    "operators_009": "def is_close_enough(a, b, tolerance):\n    return abs(a - b) <= tolerance\n",
    "operators_010": "def total_area_two_rectangles(w1, h1, w2, h2):\n    return w1 * h1 + w2 * h2\n",
    "operators_011": "def percentage_change(old_value, new_value):\n    return (new_value - old_value) / old_value * 100\n",
    "operators_012": "def is_multiple_of_either(n, a, b):\n    return n % a == 0 or n % b == 0\n",
    "operators_013": "def last_two_digits(n):\n    return n % 100\n",
    "operators_014": "def round_down_to_nearest(n, multiple):\n    return (n // multiple) * multiple\n",
    "operators_015": "def round_up_to_nearest(n, multiple):\n    return ((n + multiple - 1) // multiple) * multiple\n",
    "operators_016": "def exponential_growth(initial, rate, periods):\n    return initial * (1 + rate) ** periods\n",
    "operators_017": "def should_send_alert(is_critical, is_acknowledged):\n    return is_critical and not is_acknowledged\n",
    "operators_018": "def harmonic_mean_of_two(a, b):\n    return 2 * a * b / (a + b)\n",
    "operators_019": "def body_mass_index(weight_kg, height_m):\n    return weight_kg / (height_m ** 2)\n",
    "operators_020": "def is_right_triangle(a, b, c):\n    return a ** 2 + b ** 2 == c ** 2\n",
    "operators_debug_001": "def percentage_change(old_value, new_value):\n    return (new_value - old_value) / old_value * 100\n",
    "operators_debug_002": "def is_close_enough(a, b, tolerance):\n    return abs(a - b) <= tolerance\n",
    "operators_debug_003": "def round_down_to_nearest(n, multiple):\n    return (n // multiple) * multiple\n",
    "operators_debug_004": "def is_right_triangle(a, b, c):\n    return a ** 2 + b ** 2 == c ** 2\n",

    # Conditionals (04_conditionals)
    "conditionals_001": "def grade_from_score(score):\n    if score >= 90:\n        return 'A'\n    elif score >= 80:\n        return 'B'\n    elif score >= 70:\n        return 'C'\n    elif score >= 60:\n        return 'D'\n    else:\n        return 'F'\n",
    "conditionals_002": "def classify_bmi(weight_kg, height_m):\n    bmi = weight_kg / (height_m ** 2)\n    if bmi < 18.5:\n        return 'underweight'\n    elif bmi < 25:\n        return 'normal'\n    elif bmi < 30:\n        return 'overweight'\n    else:\n        return 'obese'\n",
    "conditionals_003": "def shipping_cost(weight, distance):\n    if weight <= 5 and distance <= 100:\n        return 5\n    elif weight <= 5:\n        return 10\n    elif distance <= 100:\n        return 15\n    else:\n        return 20\n",
    "conditionals_004": "def is_valid_triangle(a, b, c):\n    return a + b > c and a + c > b and b + c > a\n",
    "conditionals_005": "def ticket_price_with_group_discount(age, group_size):\n    if age < 12:\n        price = 5\n    elif age < 65:\n        price = 10\n    else:\n        price = 7\n    if group_size >= 5:\n        price = price * 0.8\n    return price\n",
    "conditionals_006": "def overtime_pay(hours, hourly_rate):\n    if hours <= 40:\n        return hours * hourly_rate\n    else:\n        regular = 40 * hourly_rate\n        overtime = (hours - 40) * hourly_rate * 1.5\n        return regular + overtime\n",
    "conditionals_007": "def is_leap_year(year):\n    if year % 4 != 0:\n        return False\n    if year % 100 != 0:\n        return True\n    return year % 400 == 0\n",
    "conditionals_008": "def password_strength(password):\n    if len(password) < 6:\n        return 'weak'\n    elif len(password) < 10:\n        return 'medium'\n    else:\n        return 'strong'\n",
    "conditionals_009": "def tax_owed(income):\n    if income <= 10000:\n        return income * 0.1\n    elif income <= 40000:\n        return 1000 + (income - 10000) * 0.2\n    else:\n        return 7000 + (income - 40000) * 0.3\n",
    "conditionals_010": "def can_checkout(cart_total, has_coupon, coupon_minimum):\n    return not has_coupon or cart_total >= coupon_minimum\n",
    "conditionals_011": "def heat_index_alert(temp, humidity):\n    return temp >= 90 and humidity >= 60\n",
    "conditionals_012": "def is_valid_day_for_month(day, month):\n    if day < 1:\n        return False\n    if month in (1, 3, 5, 7, 8, 10, 12):\n        return day <= 31\n    elif month in (4, 6, 9, 11):\n        return day <= 30\n    elif month == 2:\n        return day <= 28\n    else:\n        return False\n",
    "conditionals_013": "def performance_tier(score, threshold1, threshold2, threshold3):\n    if score >= threshold3:\n        return 4\n    elif score >= threshold2:\n        return 3\n    elif score >= threshold1:\n        return 2\n    else:\n        return 1\n",
    "conditionals_014": "def is_valid_username(username):\n    return 3 <= len(username) <= 16 and ' ' not in username\n",
    "conditionals_015": "def late_fee(days_late):\n    if days_late <= 0:\n        return 0\n    elif days_late <= 7:\n        return 5\n    elif days_late <= 30:\n        return 15\n    else:\n        return 30\n",
    "conditionals_016": "def can_move_elevator(current_floor, requested_floor, max_floor):\n    return 1 <= requested_floor <= max_floor and requested_floor != current_floor\n",
    "conditionals_017": "def discount_tier(total_spent):\n    if total_spent >= 500:\n        return 20\n    elif total_spent >= 200:\n        return 10\n    elif total_spent >= 50:\n        return 5\n    else:\n        return 0\n",
    "conditionals_018": "def is_business_day(day_name):\n    return day_name not in ('Saturday', 'Sunday')\n",
    "conditionals_019": "def compare_three_way(a, b):\n    if a < b:\n        return -1\n    elif a > b:\n        return 1\n    else:\n        return 0\n",
    "conditionals_020": "def fizz_or_buzz(n):\n    if n % 15 == 0:\n        return 'fizzbuzz'\n    elif n % 3 == 0:\n        return 'fizz'\n    elif n % 5 == 0:\n        return 'buzz'\n    else:\n        return str(n)\n",
    "conditionals_debug_001": "def grade_from_score(score):\n    if score >= 90:\n        return 'A'\n    elif score >= 80:\n        return 'B'\n    elif score >= 70:\n        return 'C'\n    elif score >= 60:\n        return 'D'\n    else:\n        return 'F'\n",
    "conditionals_debug_002": "def is_leap_year(year):\n    if year % 4 != 0:\n        return False\n    if year % 100 != 0:\n        return True\n    return year % 400 == 0\n",
    "conditionals_debug_003": "def fizz_or_buzz(n):\n    if n % 15 == 0:\n        return 'fizzbuzz'\n    elif n % 3 == 0:\n        return 'fizz'\n    elif n % 5 == 0:\n        return 'buzz'\n    else:\n        return str(n)\n",
    "conditionals_debug_004": "def compare_three_way(a, b):\n    if a < b:\n        return -1\n    elif a > b:\n        return 1\n    else:\n        return 0\n",
    "functions_001": "def lucky_number():\n    return 7\n",
    "functions_002": "def greet(name, greeting='Hello'):\n    return f'{greeting}, {name}!'\n",
    "functions_003": "def describe_person(name, age, city='Unknown'):\n    return f'{name} is {age} years old and lives in {city}.'\n",
    "functions_004": "def announce_winner(name):\n    print(f'{name} wins!')\n",
    "functions_005": "def safe_divide(a, b, default=0):\n    if b == 0:\n        return default\n    return a / b\n",
    "functions_006": "def describe_rectangle(width, height):\n    area = width * height\n    perimeter = 2 * (width + height)\n    return area, perimeter\n",
    "functions_007": "def min_and_max(nums):\n    return min(nums), max(nums)\n",
    "functions_008": "def divide_with_remainder(a, b):\n    return a // b, a % b\n",
    "functions_009": "def total_and_average(nums):\n    total = sum(nums)\n    average = total / len(nums)\n    return total, average\n",
    "functions_010": "def classify_and_count(nums):\n    positives = 0\n    negatives = 0\n    zeros = 0\n    for n in nums:\n        if n > 0:\n            positives += 1\n        elif n < 0:\n            negatives += 1\n        else:\n            zeros += 1\n    return positives, negatives, zeros\n",
    "functions_011": "def is_even(n):\n    return n % 2 == 0\n\n\ndef count_evens(nums):\n    count = 0\n    for n in nums:\n        if is_even(n):\n            count += 1\n    return count\n",
    "functions_012": "def celsius_to_fahrenheit(c):\n    return c * 9 / 5 + 32\n\n\ndef weather_report(c):\n    f = celsius_to_fahrenheit(c)\n    return f\"It's {f} degrees Fahrenheit.\"\n",
    "functions_013": "def square(n):\n    return n * n\n\n\ndef sum_of_squares(nums):\n    total = 0\n    for n in nums:\n        total += square(n)\n    return total\n",
    "functions_014": "def area_of_square(side):\n    return side * side\n\n\ndef total_area_of_squares(sides):\n    total = 0\n    for side in sides:\n        total += area_of_square(side)\n    return total\n",
    "functions_015": "def is_valid_password_length(pw):\n    return len(pw) >= 8\n\n\ndef all_passwords_valid(passwords):\n    for pw in passwords:\n        if not is_valid_password_length(pw):\n            return False\n    return True\n",
    "functions_016": "def celsius_to_fahrenheit(c):\n    return c * 9 / 5 + 32\n\n\ndef fahrenheit_report_list(celsius_list):\n    result = []\n    for c in celsius_list:\n        result.append(celsius_to_fahrenheit(c))\n    return result\n",
    "functions_017": "def is_passing(score):\n    return score >= 60\n\n\ndef count_passing_scores(scores):\n    count = 0\n    for score in scores:\n        if is_passing(score):\n            count += 1\n    return count\n",
    "functions_018": "def total_cost(price, quantity):\n    return price * quantity\n\n\ndef total_cost_for_order(prices, quantities):\n    total = 0\n    for i in range(len(prices)):\n        total += total_cost(prices[i], quantities[i])\n    return total\n",
    "functions_019": "def discounted_price(price, discount_percent):\n    return price - price * discount_percent / 100\n\n\ndef apply_discount_twice(price, discount_percent):\n    once = discounted_price(price, discount_percent)\n    twice = discounted_price(once, discount_percent)\n    return twice\n",
    "functions_020": "def total_cost(price, quantity):\n    return price * quantity\n\n\ndef format_receipt(item, price, quantity):\n    cost = total_cost(price, quantity)\n    return f'{quantity}x {item}: ${cost}'\n",
    "functions_debug_001": "def safe_divide(a, b, default=0):\n    if b == 0:\n        return default\n    return a / b\n",
    "functions_debug_002": "def describe_rectangle(width, height):\n    area = width * height\n    perimeter = 2 * (width + height)\n    return area, perimeter\n",
    "functions_debug_003": "def is_even(n):\n    return n % 2 == 0\n\n\ndef count_evens(nums):\n    count = 0\n    for n in nums:\n        if is_even(n):\n            count += 1\n    return count\n",
    "functions_debug_004": "def total_and_average(nums):\n    total = sum(nums)\n    average = total / len(nums)\n    return total, average\n",
    "strings_001": "def reverse_string(s):\n    return s[::-1]\n",
    "strings_002": "def is_palindrome(s):\n    return s == s[::-1]\n",
    "strings_003": "def count_character(s, ch):\n    return s.count(ch)\n",
    "strings_004": "def first_and_last_char(s):\n    return s[0] + s[-1]\n",
    "strings_005": "def remove_spaces(s):\n    return s.replace(' ', '')\n",
    "strings_006": "def contains_substring(s, sub):\n    return sub in s\n",
    "strings_007": "def slice_middle(s):\n    return s[1:-1]\n",
    "strings_008": "def count_words(s):\n    return len(s.split())\n",
    "strings_009": "def capitalize_first_letter(s):\n    return s[0].upper() + s[1:]\n",
    "strings_010": "def replace_character(s, old, new):\n    return s.replace(old, new)\n",
    "strings_011": "def starts_with(s, prefix):\n    return s.startswith(prefix)\n",
    "strings_012": "def ends_with(s, suffix):\n    return s.endswith(suffix)\n",
    "strings_013": "def join_with_separator(words, separator):\n    return separator.join(words)\n",
    "strings_014": "def split_into_words(s):\n    return s.split()\n",
    "strings_015": "def is_all_digits(s):\n    return s.isdigit()\n",
    "strings_016": "def count_uppercase_letters(s):\n    count = 0\n    for ch in s:\n        if ch.isupper():\n            count += 1\n    return count\n",
    "strings_017": "def title_case(s):\n    words = s.split()\n    result = []\n    for word in words:\n        result.append(word[0].upper() + word[1:])\n    return ' '.join(result)\n",
    "strings_018": "def longest_word(s):\n    words = s.split()\n    return max(words, key=len)\n",
    "strings_019": "def remove_character(s, ch):\n    result = ''\n    for c in s:\n        if c != ch:\n            result += c\n    return result\n",
    "strings_020": "def is_anagram(a, b):\n    return sorted(a) == sorted(b)\n",
    "strings_debug_001": "def reverse_string(s):\n    return s[::-1]\n",
    "strings_debug_002": "def count_character(s, ch):\n    return s.count(ch)\n",
    "strings_debug_003": "def capitalize_first_letter(s):\n    return s[0].upper() + s[1:]\n",
    "strings_debug_004": "def is_anagram(a, b):\n    return sorted(a) == sorted(b)\n",
    "lists_001": "def sum_of_list(nums):\n    return sum(nums)\n",
    "lists_002": "def average_of_list(nums):\n    return sum(nums) / len(nums)\n",
    "lists_003": "def find_maximum(nums):\n    return max(nums)\n",
    "lists_004": "def find_minimum(nums):\n    return min(nums)\n",
    "lists_005": "def count_occurrences(nums, target):\n    return nums.count(target)\n",
    "lists_006": "def contains_value(nums, target):\n    return target in nums\n",
    "lists_007": "def index_of_value(nums, target):\n    return nums.index(target)\n",
    "lists_008": "def reverse_list(nums):\n    return nums[::-1]\n",
    "lists_009": "def first_n_elements(nums, n):\n    return nums[:n]\n",
    "lists_010": "def last_n_elements(nums, n):\n    return nums[-n:]\n",
    "lists_011": "def append_value(nums, value):\n    nums.append(value)\n    return nums\n",
    "lists_012": "def remove_value(nums, value):\n    nums.remove(value)\n    return nums\n",
    "lists_013": "def double_each_element(nums):\n    result = []\n    for n in nums:\n        result.append(n * 2)\n    return result\n",
    "lists_014": "def filter_evens(nums):\n    result = []\n    for n in nums:\n        if n % 2 == 0:\n            result.append(n)\n    return result\n",
    "lists_015": "def filter_greater_than(nums, threshold):\n    result = []\n    for n in nums:\n        if n > threshold:\n            result.append(n)\n    return result\n",
    "lists_016": "def count_positive(nums):\n    count = 0\n    for n in nums:\n        if n > 0:\n            count += 1\n    return count\n",
    "lists_017": "def squares_of_list(nums):\n    result = []\n    for n in nums:\n        result.append(n * n)\n    return result\n",
    "lists_018": "def merge_two_lists(a, b):\n    return a + b\n",
    "lists_019": "def remove_duplicates(nums):\n    result = []\n    for n in nums:\n        if n not in result:\n            result.append(n)\n    return result\n",
    "lists_020": "def second_largest(nums):\n    first = max(nums[0], nums[1])\n    second = min(nums[0], nums[1])\n    for n in nums[2:]:\n        if n > first:\n            second = first\n            first = n\n        elif n > second:\n            second = n\n    return second\n",
    "lists_debug_001": "def find_maximum(nums):\n    return max(nums)\n",
    "lists_debug_002": "def filter_evens(nums):\n    result = []\n    for n in nums:\n        if n % 2 == 0:\n            result.append(n)\n    return result\n",
    "lists_debug_003": "def remove_duplicates(nums):\n    result = []\n    for n in nums:\n        if n not in result:\n            result.append(n)\n    return result\n",
    "lists_debug_004": "def second_largest(nums):\n    first = max(nums[0], nums[1])\n    second = min(nums[0], nums[1])\n    for n in nums[2:]:\n        if n > first:\n            second = first\n            first = n\n        elif n > second:\n            second = n\n    return second\n",
    "dictionaries_001": "def get_value(d, key):\n    return d[key]\n",
    "dictionaries_002": "def has_key(d, key):\n    return key in d\n",
    "dictionaries_003": "def add_or_update(d, key, value):\n    d[key] = value\n    return d\n",
    "dictionaries_004": "def remove_key(d, key):\n    del d[key]\n    return d\n",
    "dictionaries_005": "def count_keys(d):\n    return len(d)\n",
    "dictionaries_006": "def get_with_default(d, key, default):\n    return d.get(key, default)\n",
    "dictionaries_007": "def all_keys(d):\n    return list(d.keys())\n",
    "dictionaries_008": "def all_values(d):\n    return list(d.values())\n",
    "dictionaries_009": "def sum_of_values(d):\n    return sum(d.values())\n",
    "dictionaries_010": "def max_value_key(d):\n    return max(d, key=d.get)\n",
    "dictionaries_011": "def count_word_frequencies(words):\n    freq = {}\n    for word in words:\n        freq[word] = freq.get(word, 0) + 1\n    return freq\n",
    "dictionaries_012": "def merge_dicts(a, b):\n    result = dict(a)\n    for key in b:\n        result[key] = b[key]\n    return result\n",
    "dictionaries_013": "def invert_dict(d):\n    result = {}\n    for key in d:\n        result[d[key]] = key\n    return result\n",
    "dictionaries_014": "def filter_by_value_threshold(d, threshold):\n    result = {}\n    for key in d:\n        if d[key] > threshold:\n            result[key] = d[key]\n    return result\n",
    "dictionaries_015": "def increment_value(d, key):\n    d[key] += 1\n    return d\n",
    "dictionaries_016": "def keys_with_value(d, target_value):\n    result = []\n    for key in d:\n        if d[key] == target_value:\n            result.append(key)\n    return result\n",
    "dictionaries_017": "def average_of_values(d):\n    return sum(d.values()) / len(d)\n",
    "dictionaries_018": "def combine_counts(d, key, amount):\n    d[key] = d.get(key, 0) + amount\n    return d\n",
    "dictionaries_019": "def dict_from_two_lists(keys, values):\n    result = {}\n    for i in range(len(keys)):\n        result[keys[i]] = values[i]\n    return result\n",
    "dictionaries_020": "def count_matching_values(d, target):\n    count = 0\n    for key in d:\n        if d[key] == target:\n            count += 1\n    return count\n",
    "dictionaries_debug_001": "def get_with_default(d, key, default):\n    return d.get(key, default)\n",
    "dictionaries_debug_002": "def merge_dicts(a, b):\n    result = dict(a)\n    for key in b:\n        result[key] = b[key]\n    return result\n",
    "dictionaries_debug_003": "def invert_dict(d):\n    result = {}\n    for key in d:\n        result[d[key]] = key\n    return result\n",
    "dictionaries_debug_004": "def count_matching_values(d, target):\n    count = 0\n    for key in d:\n        if d[key] == target:\n            count += 1\n    return count\n",
    "tuples_001": "def unpack_pair(pair):\n    a, b = pair\n    return a + b\n",
    "tuples_002": "def get_element_at(t, index):\n    return t[index]\n",
    "tuples_003": "def tuple_length(t):\n    return len(t)\n",
    "tuples_004": "def swap_pair(pair):\n    a, b = pair\n    return b, a\n",
    "tuples_005": "def make_point(x, y):\n    return (x, y)\n",
    "tuples_006": "def distance_squared_between_points(p1, p2):\n    x1, y1 = p1\n    x2, y2 = p2\n    return (x2 - x1) ** 2 + (y2 - y1) ** 2\n",
    "tuples_007": "def tuple_to_list(t):\n    return list(t)\n",
    "tuples_008": "def list_to_tuple(lst):\n    return tuple(lst)\n",
    "tuples_009": "def concatenate_tuples(a, b):\n    return a + b\n",
    "tuples_010": "def count_value_in_tuple(t, value):\n    return t.count(value)\n",
    "tuples_011": "def index_of_value_in_tuple(t, value):\n    return t.index(value)\n",
    "tuples_012": "def first_and_last(t):\n    return (t[0], t[-1])\n",
    "tuples_013": "def slice_tuple(t, start, end):\n    return t[start:end]\n",
    "tuples_014": "def sum_of_tuple(t):\n    return sum(t)\n",
    "tuples_015": "def max_of_tuple(t):\n    return max(t)\n",
    "tuples_016": "def pairs_from_two_lists(a, b):\n    return list(zip(a, b))\n",
    "tuples_017": "def sum_of_pairs(pairs):\n    result = []\n    for a, b in pairs:\n        result.append(a + b)\n    return result\n",
    "tuples_018": "def swap_first_last(t):\n    t_list = list(t)\n    t_list[0], t_list[-1] = t_list[-1], t_list[0]\n    return tuple(t_list)\n",
    "tuples_019": "def tuples_are_equal(a, b):\n    return a == b\n",
    "tuples_020": "def sort_tuples_by_second(pairs):\n    return sorted(pairs, key=lambda p: p[1])\n",
    "tuples_debug_001": "def swap_pair(pair):\n    a, b = pair\n    return b, a\n",
    "tuples_debug_002": "def concatenate_tuples(a, b):\n    return a + b\n",
    "tuples_debug_003": "def first_and_last(t):\n    return (t[0], t[-1])\n",
    "tuples_debug_004": "def sum_of_pairs(pairs):\n    result = []\n    for a, b in pairs:\n        result.append(a + b)\n    return result\n",
    "nested_001": "def get_grid_value(grid, row, col):\n    return grid[row][col]\n",
    "nested_002": "def sum_of_grid(grid):\n    total = 0\n    for row in grid:\n        for val in row:\n            total += val\n    return total\n",
    "nested_003": "def flatten_grid(grid):\n    result = []\n    for row in grid:\n        for val in row:\n            result.append(val)\n    return result\n",
    "nested_004": "def row_sums(grid):\n    result = []\n    for row in grid:\n        result.append(sum(row))\n    return result\n",
    "nested_005": "def column_sum(grid, col_index):\n    total = 0\n    for row in grid:\n        total += row[col_index]\n    return total\n",
    "nested_006": "def transpose_grid(grid):\n    result = []\n    for col in range(len(grid[0])):\n        new_row = []\n        for row in grid:\n            new_row.append(row[col])\n        result.append(new_row)\n    return result\n",
    "nested_007": "def max_in_grid(grid):\n    best = grid[0][0]\n    for row in grid:\n        for val in row:\n            if val > best:\n                best = val\n    return best\n",
    "nested_008": "def count_matching_in_grid(grid, target):\n    count = 0\n    for row in grid:\n        for val in row:\n            if val == target:\n                count += 1\n    return count\n",
    "nested_009": "def diagonal_sum(grid):\n    total = 0\n    for i in range(len(grid)):\n        total += grid[i][i]\n    return total\n",
    "nested_010": "def get_student_field(students, index, field):\n    return students[index][field]\n",
    "nested_011": "def total_score(students, field):\n    total = 0\n    for s in students:\n        total += s[field]\n    return total\n",
    "nested_012": "def names_of_students(students):\n    result = []\n    for s in students:\n        result.append(s['name'])\n    return result\n",
    "nested_013": "def filter_students_by_min_score(students, min_score):\n    result = []\n    for s in students:\n        if s['score'] >= min_score:\n            result.append(s['name'])\n    return result\n",
    "nested_014": "def average_field(students, field):\n    total = 0\n    for s in students:\n        total += s[field]\n    return total / len(students)\n",
    "nested_015": "def get_nested_dict_value(data, outer_key, inner_key):\n    return data[outer_key][inner_key]\n",
    "nested_016": "def add_score_to_student(students, index, points):\n    students[index]['score'] += points\n    return students\n",
    "nested_017": "def group_totals(groups):\n    result = {}\n    for key in groups:\n        result[key] = sum(groups[key])\n    return result\n",
    "nested_018": "def count_items_per_category(catalog):\n    result = {}\n    for key in catalog:\n        result[key] = len(catalog[key])\n    return result\n",
    "nested_019": "def find_student_with_max_score(students):\n    best = students[0]\n    for s in students:\n        if s['score'] > best['score']:\n            best = s\n    return best['name']\n",
    "nested_020": "def list_of_pairs_to_dict(pairs):\n    result = {}\n    for key, value in pairs:\n        result[key] = value\n    return result\n",
    "nested_debug_001": "def sum_of_grid(grid):\n    total = 0\n    for row in grid:\n        for val in row:\n            total += val\n    return total\n",
    "nested_debug_002": "def transpose_grid(grid):\n    result = []\n    for col in range(len(grid[0])):\n        new_row = []\n        for row in grid:\n            new_row.append(row[col])\n        result.append(new_row)\n    return result\n",
    "nested_debug_003": "def filter_students_by_min_score(students, min_score):\n    result = []\n    for s in students:\n        if s['score'] >= min_score:\n            result.append(s['name'])\n    return result\n",
    "nested_debug_004": "def diagonal_sum(grid):\n    total = 0\n    for i in range(len(grid)):\n        total += grid[i][i]\n    return total\n",
}
